# Generated by Django 5.0.7 on 2024-11-11 07:08

import anusha.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anusha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('reason_to_connect', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='dsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('pan', models.CharField(blank=True, max_length=12, null=True)),
                ('aadhar', models.CharField(max_length=12)),
                ('profession', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('acc_number', models.CharField(max_length=30)),
                ('acc_holder_name', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=40)),
                ('branch_name', models.CharField(max_length=20)),
                ('agreeCheck', models.BooleanField(default=False)),
                ('franchiserefcode', models.CharField(blank=True, max_length=400, null=True)),
                ('dsa_id', models.CharField(blank=True, max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('pan', models.CharField(blank=True, max_length=12, null=True)),
                ('aadhar', models.CharField(max_length=12)),
                ('profession', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('agreeCheck', models.BooleanField(default=False)),
                ('dsaPhoto', models.ImageField(upload_to='dsa/', validators=[anusha.models.validate_image_file])),
                ('aadharFront', models.ImageField(upload_to='dsa/', validators=[anusha.models.validate_image_file])),
                ('aadharBack', models.ImageField(upload_to='dsa/', validators=[anusha.models.validate_image_file])),
                ('panCard', models.ImageField(upload_to='dsa/', validators=[anusha.models.validate_image_file])),
                ('bankDocument', models.ImageField(upload_to='dsa/', validators=[anusha.models.validate_image_file])),
                ('franchiserefcode', models.CharField(blank=True, max_length=500, null=True)),
                ('franchise_id', models.CharField(blank=True, max_length=15, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='allinsurance',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='generalinsurance',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='healthinsurance',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lifeinsurance',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicdetailform',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='basicdetailform',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='goldbasicdetailform',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='goldbasicdetailform',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='otherbasicdetailform',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='otherbasicdetailform',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=10, null=True),
        ),
    ]
