# Generated by Django 5.0.7 on 2024-11-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anusha', '0002_contactsubmission_dsa_franchise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicdetailform',
            name='expiry_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goldbasicdetailform',
            name='expiry_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherbasicdetailform',
            name='expiry_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicdetailform',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='goldbasicdetailform',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='otherbasicdetailform',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
