# Generated by Django 5.0.7 on 2024-11-14 01:33

import anusha.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anusha', '0006_alter_loanapplication_co_applicant_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='co_applicant_mobile_number',
            field=models.CharField(default='', max_length=10, validators=[anusha.models.validate_mobile_number]),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[anusha.models.validate_mobile_number]),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='ref1_mobile',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[anusha.models.validate_mobile_number]),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='ref2_mobile',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[anusha.models.validate_mobile_number]),
        ),
    ]
